import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import './globals.css'

import { PropsWithChildren } from 'react'

const roboto = Roboto({
  variable: '--font-primary',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>{children}</body>
    </html>
  )
}
